#! /bin/bash

echo "Enter Database to connect"
read data_base_name 
while [ ! -d "$data_base_name" ]
do
	echo "this database doesnt exist"
	echo "please try again"
	read data_base_name
done

cd "$data_base_name" 
echo "$data_base_name connected successfully"

PS3="Pick a database task (enter the number): "
select option in "create" "list" "drop" "insert" "select" "delete" "quit"
do 
	case $option in 
	"create") 
	 echo "Create table" ;;
	"list") 
	 echo "list table" ;;
	"drop") 
	 echo "drop table";;
	"insert") 
	 echo "insert table";;
	 "select")
	 echo "select table";;
	"delete") 
	 echo "delete table";;
	"quit")
	 echo "good bye"
	 break;;
	*) #handle invalid options
	 echo "invalid option";;
	esac 
done

