#! /bin/bash


echo "Enter name to connect"
read data_base_name

valid=$( ../tableAndDBNamingValidations.sh $data_base_name ) 



while [ ! -d $data_base_name ]
do
valid=$( ../tableAndDBNamingValidations.sh $data_base_name ) 
	while (( valid != 0 )) 
do
  echo $valid
	echo "Invalid name"
	echo "Please try again"
	read data_base_name
	valid=$( ../tableAndDBNamingValidations.sh $data_base_name )
done
	echo "This database doesnt exist"
	echo "Please try again"
	read data_base_name
done

cd $data_base_name 
echo "$data_base_name connected successfully"

PS3="Pick a database task (enter the number): "
select option in "createTable" "listTables" "dropTables" "insertIntoTables" "selectFromTables" "updateTable" "deleteTable" "quit"
do 
	case $option in 
	"createTable") 
	 ../../create_table 
	 ;;
	"listTables") 
	 ../../listTable.sh $data_base_name 
	  ;;
	"dropTables") 
	 ../../dropTable.sh $data_base_name 
	 ;;
	"insertIntoTables") 
	 ../../insert
	 ;;
	 "selectFromTables")
	 ../../selectFromTable.sh
	 ;;
	"deleteTable") 
	 ../../delete_data
	 ;;
	"updateTable") 
	 ../../updateTable.sh;;
	"quit")
	 echo "good bye"
	 break;;
	*) #handle invalid options
	 echo "invalid option";;
	esac 
done

