#! /bin/bash
cd DB

echo "Enter name to connect"
read data_base_name

valid=$( ../tableAndDBNamingValidations.sh $data_base_name ) 



while [ ! -d $data_base_name ]
do
valid=$( ../tableAndDBNamingValidations.sh $data_base_name ) 
	while (( valid != 0 )) 
do
  echo $valid
	echo "Invalid name"
	echo "Please try again"
	read data_base_name
	valid=$( ../tableAndDBNamingValidations.sh $data_base_name )
done
	echo "This database doesnt exist"
	echo "Please try again"
	read data_base_name
done

cd $data_base_name 
echo "$data_base_name connected successfully"

PS3="Pick a database task (enter the number): "
select option in "create" "list" "drop" "insert" "select" "delete" "quit"
do 
	case $option in 
	"create") 
	 echo "Create table" ;;
	"list") 
	 echo "list table" ;;
	"drop") 
	 echo "drop table";;
	"insert") 
	 echo "insert table";;
	 "select")
	 echo "select table";;
	"delete") 
	 echo "delete table";;
	"quit")
	 echo "good bye"
	 break;;
	*) #handle invalid options
	 echo "invalid option";;
	esac 
done

