#! /bin/bash

echo "Enter the table name:"
read table_name

# -e is to make sure that table name is unique
while [[ -e "$table_name" ]]
do
  echo "Error: $table_name already exists in the current database."
  echo "Please enter a different table name :"
  read table_name
done

# Ask for the number of columns
echo "Enter the number of columns:"
read num_columns

# Initialize an empty string for the column names
# this is to allow column_name with spaces in it
columns=""

# Loop over the number of columns
for (( i=1; i<=num_columns; i++ ))
  do
      # Ask for the column name
      echo "Enter name for column $i:"
      read column_name

      # Initialize a variable for the data type
      data_type=""

          # Display the data type menu
          echo "Select data type for column $i:"
          echo "1. int"
          echo "2. string"

          read selection

          case $selection in
            1) data_type="int" ;;
            2) data_type="string" ;;
            *) echo "Invalid selection. Please choose 1 for int or 2 for string." ;;
          esac
          
    columns+="$column_name($data_type),"
  done

columns=${columns%?}
# another method is to use columns=${columns:0:-n}
# where 0 is the index (starting from the last character ) and n is the number of characters to be removed


echo $columns > "$table_name.table"

while true
  do
  echo "Now choose your primary key:"
  echo "Available columns:"  
    IFS=,
    read -ra column_array <<< "$columns"
    for (( i=0; i<${#column_array[@]}; i++ ))
    do
      echo "$((i+1)). ${column_array[i]}"
    done
  read primary_key_selection

    # Check if the selection is valid
        if [[ $primary_key_selection -ge 1 && $primary_key_selection -le ${#column_array[@]} ]]
        then
          primary_key=${column_array[$((primary_key_selection-1))]}
          echo "You selected $primary_key as the primary key"
          break
        else
          echo "Invalid selection. Please try again."
        fi
  done

echo $primary_key >> $table_name.table



echo "Table $table_name created with columns: $columns"
echo " with $primary_key as the primary key"
