#!/bin/bash

echo "Enter the table name:"
read table_name

# -e is to make sure that table name is unique
while [[ -e "$table_name" ]]
do
  echo "Error: $table_name already exists in the current database."
  echo "Please enter a different table name :"
  read table_name
done

# Ask for the number of columns
echo "Enter the number of columns:"
read num_columns

# Initialize an empty string for the column names
# this is to allow column_name with spaces in it
columns=""

# Loop over the number of columns
for (( i=1; i<=num_columns; i++ ))
do
  # Ask for the column name
  echo "Enter name for column $i:"
  read column_name

  # Initialize a variable for the data type
  data_type=""

  # Keep asking for the data type until a valid selection is made
  while [[ $data_type != "int" && $data_type != "string" ]]
  do
    # Display the data type menu
    echo "Select data type for column $i:"
    echo "1. int"
    echo "2. string"

    read selection

    case $selection in
      1) data_type="int" ;;
      2) data_type="string" ;;
      *) echo "Invalid selection. Please choose 1 for int or 2 for string." ;;
    esac
  done

  columns+="$column_name($data_type),"

done

columns=${columns%?}
# another method is to use columns=${columns:0:-n}
#where 0 is the index (starting from the last character ) and n is the number of characters to be removed


echo $columns > "$table_name.file"

echo "Table $table_name created with columns: $columns"
