#!/bin/bash

shopt -s nullglob
tables=( *.table )


# Check if there are any tables
if [[ ${#tables[@]} -eq 0 ]]
then
  echo "No tables found."
  exit
fi

# Display the tables

#  ${} --> means variable 
#  # -> means number
#  tables[@] --> means each member of the array
  echo "Available tables:"
  for (( i=0; i<${#tables[@]}; i++ ))
    do
      echo "$((i+1)). ${tables[i]}"
    done


# Ask for the table selection
while true; do
  echo "Enter the number of the table you want to manage:"
  read selection
      while ! [[ $selection =~ ^[1-9]+$ ]]; do
          echo "Error: $selection must be positive."
          echo "Please try again."
          read selection
          while [[ -z $selection ]]
          do
            echo "Cannot be Empty !! "
            echo "Please try again."
            read selection
          done
      done

  # Check if the selection is valid
  if [[ $selection -ge 1 && $selection -le ${#tables[@]} ]]; then
    table_name=${tables[$((selection-1))]}
    echo "You selected $table_name"
    break
  else
    echo "Invalid selection. Please try again."
  fi
done

# Display options for managing the table

    echo "Select an option:"
    echo "1. Delete a specific row"
    echo "2. Delete all data"
    echo "3. Delete all specific column"
    read option

    while ! [[ $option =~ ^[1-9]+$ ]]; do
        echo "Error: $selection must be positive."
        echo "Please try again."
        read option
        while [[ -z $option ]]
        do
          echo "Cannot be Empty !! "
          echo "Please try again."
          read option
        done
    done


case $option in
  1)
    # Delete a specific row
    echo "Enter the row number to delete:"
    read row_number

    # Check if it's the first row
    while [[ $row_number -eq 1 ]]
    do
      echo "Cannot delete the first row"
      echo "Enter row number to delete"
      read row_number
    done

    # -i option with sed to edit the file inplace without openning 
    # {} can be removed and the script will work just fine but they are added to avoid any confusion in more complex expressions
    sed -i "${row_number}d" "$table_name"
    echo "Row $row_number deleted from $table_name"
    ;;

  2)
    # Delete all rows (except first row)
    sed -i '2,$d' "$table_name"
    echo "Data of $table_name deleted successfully"
    ;;

  3)
    # Delete an entire column
    echo "Enter the name of the column to delete:"
    read column_name

    # -i option with sed to edit the file inplace without opening
    sed -i "s/[^,]*$column_name[^,]*,//" "$table_name"
    echo "Column $column_name deleted from $table_name"
    ;;

  *)
    echo "Invalid option."
      echo "Select a valid option:"
      echo "1. Delete a specific row"
      echo "2. Delete all data"
      echo "3. Delete an entire column"
      read option
    ;;
esac
